CREATE TABLE `multiplayer_rooms` (
	`id` varchar(128) NOT NULL,
	`roomCode` varchar(6) NOT NULL,
	`hostUserId` int NOT NULL,
	`guestUserId` int,
	`mode` varchar(32) NOT NULL,
	`status` enum('lobby','playing','complete') NOT NULL DEFAULT 'lobby',
	`currentQuestionIndex` int NOT NULL DEFAULT 0,
	`hostReady` int NOT NULL DEFAULT 0,
	`guestReady` int NOT NULL DEFAULT 0,
	`hostAnsweredIndex` int NOT NULL DEFAULT -1,
	`guestAnsweredIndex` int NOT NULL DEFAULT -1,
	`hostScore` int NOT NULL DEFAULT 0,
	`guestScore` int NOT NULL DEFAULT 0,
	`winnerUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `multiplayer_rooms_id` PRIMARY KEY(`id`),
	CONSTRAINT `multiplayer_rooms_roomCode_unique` UNIQUE(`roomCode`)
);
