import { randomUUID } from "node:crypto";
import { and, desc, eq, gt, gte, inArray, lte, ne, or, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { friendChallenges, InsertUser, matchmakingQueue, multiplayerMatches, multiplayerRooms, playerProgress, sessionRecords, tournamentSeasons, users, type FriendChallenge } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { VERIFIED_BIBLE_QUIZ_QUESTIONS, type GameMode } from "../domain/questions";
import { getMatchXp, getRematchPatch, getRoomReadyPatch, getTimeoutPatch, resolveRoomAnswer, MULTIPLAYER_ROUND_DURATION_MS } from "../domain/multiplayer";
import { broadcastRoom } from "./realtime";
import { aggregateMultiplayerRankings, type MultiplayerRankingScope } from "../domain/multiplayer-rankings";
import { findQueueMatch, MATCHMAKING_QUEUE_TTL_MS, ratingFromRanking } from "../domain/ranked-competition";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) { console.warn("[Database] Cannot upsert user: database not available"); return; } const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } } values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getCloudProgress(userId: number) { const db = await getDb(); if (!db) return null; const [progress] = await db.select().from(playerProgress).where(eq(playerProgress.userId, userId)).limit(1); const sessions = await db.select().from(sessionRecords).where(eq(sessionRecords.userId, userId)).orderBy(desc(sessionRecords.completedAt)).limit(50); return { progress: progress ?? null, sessions }; }
export async function saveCloudProgress(input: { userId: number; totalXp: number; currentStreak: number; bestStreak: number; lastEligibleDate: string | null; achievementsJson: string }) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(playerProgress).values({ ...input }).onDuplicateKeyUpdate({ set: { totalXp: input.totalXp, currentStreak: input.currentStreak, bestStreak: input.bestStreak, lastEligibleDate: input.lastEligibleDate, achievementsJson: input.achievementsJson } }); }
export async function saveSessionRecord(input: { id: string; userId: number; mode: string; score: number; accuracy: number; correctAnswers: number; totalQuestions: number; xpEarned: number; completedAt: Date }) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(sessionRecords).values(input).onDuplicateKeyUpdate({ set: { id: input.id } }); }
export async function listUserChallenges(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(friendChallenges).where(or(eq(friendChallenges.creatorUserId, userId), eq(friendChallenges.opponentUserId, userId))).orderBy(desc(friendChallenges.createdAt)).limit(50); }
export async function createCloudChallenge(input: { id: string; shareCode: string; creatorUserId: number; mode: string; expiresAt: Date; createdAt: Date }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const challenge = { ...input, status: "open" as const }; await db.insert(friendChallenges).values(challenge); return challenge; }
export async function joinCloudChallenge(shareCode: string, opponentUserId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [challenge] = await db.select().from(friendChallenges).where(eq(friendChallenges.shareCode, shareCode)).limit(1); if (!challenge) throw new Error("Challenge not found."); if (challenge.status !== "open") throw new Error("Challenge is no longer open."); if (challenge.expiresAt <= new Date()) throw new Error("Challenge has expired."); await db.update(friendChallenges).set({ opponentUserId, status: "completed" }).where(eq(friendChallenges.id, challenge.id)); return { ...challenge, opponentUserId, status: "completed" as const }; }
export async function getLeaderboardRows(scope: "weekly" | "all_time", now: Date) { const db = await getDb(); if (!db) return []; const weekStart = new Date(now); const day = weekStart.getDay(); weekStart.setHours(0, 0, 0, 0); weekStart.setDate(weekStart.getDate() - ((day + 6) % 7)); const where = scope === "weekly" ? gte(sessionRecords.completedAt, weekStart) : undefined; const score = sql<number>`sum(${sessionRecords.score})`; const averageAccuracy = sql<number>`round(avg(${sessionRecords.accuracy}))`; const sessions = sql<number>`count(*)`; return db.select({ userId: sessionRecords.userId, displayName: users.name, score, averageAccuracy, sessions }).from(sessionRecords).leftJoin(users, eq(sessionRecords.userId, users.id)).where(where).groupBy(sessionRecords.userId, users.name).orderBy(desc(score)).limit(50); }
export async function listUserMatches(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(multiplayerMatches).where(or(eq(multiplayerMatches.hostUserId, userId), eq(multiplayerMatches.guestUserId, userId))).orderBy(desc(multiplayerMatches.completedAt)).limit(50); }
export function getSeasonDescriptor(now: Date) { const startsAt = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); const endsAt = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)); const id = `season-${startsAt.getUTCFullYear()}-${String(startsAt.getUTCMonth() + 1).padStart(2, "0")}`; return { id, name: `Season ${startsAt.getUTCFullYear()}-${String(startsAt.getUTCMonth() + 1).padStart(2, "0")}`, startsAt, endsAt }; }
export async function getMultiplayerRankingRows(scope: MultiplayerRankingScope, now: Date) {
  const db = await getDb(); if (!db) return [];
  const weekStart = new Date(now); const day = weekStart.getDay(); weekStart.setHours(0, 0, 0, 0); weekStart.setDate(weekStart.getDate() - ((day + 6) % 7));
  const season = getSeasonDescriptor(now); const where = scope === "weekly" ? gte(multiplayerMatches.completedAt, weekStart) : scope === "season" ? eq(multiplayerMatches.seasonId, season.id) : undefined;
  const matches = await db.select().from(multiplayerMatches).where(where).orderBy(desc(multiplayerMatches.completedAt)).limit(10_000);
  const ids = Array.from(new Set(matches.flatMap((match) => [match.hostUserId, match.guestUserId]))); const people = ids.length ? await db.select({ id: users.id, name: users.name }).from(users).where(inArray(users.id, ids)) : []; const names = new Map(people.map((person) => [person.id, person.name || "Bible Arena Player"]));
  return aggregateMultiplayerRankings(matches, names);
}
export async function rolloverExpiredSeasons(now = new Date()) { const db = await getDb(); const current = getSeasonDescriptor(now); if (!db) return { completed: 0, activeSeasonId: current.id }; const [result] = await db.update(tournamentSeasons).set({ status: "completed" }).where(and(eq(tournamentSeasons.status, "active"), lte(tournamentSeasons.endsAt, now))); await db.insert(tournamentSeasons).values({ ...current, status: "active" as const }).onDuplicateKeyUpdate({ set: { status: "active" } }); return { completed: Number(result.affectedRows ?? 0), activeSeasonId: current.id }; }
export async function joinMatchmakingQueue(userId: number, now = new Date()) {
  const db = await getDb(); if (!db) throw new Error("Database not available"); await rolloverExpiredSeasons(now); const season = getSeasonDescriptor(now); const rows = await getMultiplayerRankingRows("season", now); const profile = rows.find((row) => row.playerId === String(userId)); const division = profile?.division ?? "Bronze"; const rating = profile ? ratingFromRanking(profile) : 0; const entry = { id: `queue-${userId}`, userId, seasonId: season.id, division, rating, status: "waiting" as const, matchedRoomId: null, createdAt: now, expiresAt: new Date(now.getTime() + MATCHMAKING_QUEUE_TTL_MS) }; await db.insert(matchmakingQueue).values(entry).onDuplicateKeyUpdate({ set: { seasonId: season.id, division, rating, status: "waiting", matchedRoomId: null, createdAt: now, expiresAt: entry.expiresAt } }); const candidates = await db.select().from(matchmakingQueue).where(and(eq(matchmakingQueue.status, "waiting"), eq(matchmakingQueue.seasonId, season.id), ne(matchmakingQueue.userId, userId), gt(matchmakingQueue.expiresAt, now))).orderBy(matchmakingQueue.createdAt).limit(50); const opponent = findQueueMatch(entry, candidates, now); if (!opponent) return { status: "waiting" as const, queueId: entry.id, seasonId: season.id, division, rating, expiresAt: entry.expiresAt, roomId: null }; const room = await createMultiplayerRoom(userId, "bible_quiz"); const [opponentWrite] = await db.update(matchmakingQueue).set({ status: "matched", matchedRoomId: room.id }).where(and(eq(matchmakingQueue.id, opponent.id), eq(matchmakingQueue.status, "waiting"))); if (!opponentWrite.affectedRows) return { status: "waiting" as const, queueId: entry.id, seasonId: season.id, division, rating, expiresAt: entry.expiresAt, roomId: null }; await db.update(matchmakingQueue).set({ status: "matched", matchedRoomId: room.id }).where(and(eq(matchmakingQueue.id, entry.id), eq(matchmakingQueue.status, "waiting"))); await joinMultiplayerRoom(room.roomCode, opponent.userId); return { status: "matched" as const, queueId: entry.id, seasonId: season.id, division, rating, expiresAt: entry.expiresAt, roomId: room.id };
}
export async function getMatchmakingQueueStatus(userId: number, now = new Date()) { const db = await getDb(); if (!db) return null; const [entry] = await db.select().from(matchmakingQueue).where(eq(matchmakingQueue.userId, userId)).limit(1); if (!entry) return null; if (entry.status === "waiting" && entry.expiresAt <= now) { await db.update(matchmakingQueue).set({ status: "expired" }).where(and(eq(matchmakingQueue.id, entry.id), eq(matchmakingQueue.status, "waiting"))); return { ...entry, status: "expired" as const }; } return entry; }
export async function leaveMatchmakingQueue(userId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(matchmakingQueue).set({ status: "expired" }).where(and(eq(matchmakingQueue.userId, userId), eq(matchmakingQueue.status, "waiting"))); return { success: true as const }; }
export async function expireMatchmakingQueue(now = new Date()) { const db = await getDb(); if (!db) return { expired: 0 }; const [result] = await db.update(matchmakingQueue).set({ status: "expired" }).where(and(eq(matchmakingQueue.status, "waiting"), lte(matchmakingQueue.expiresAt, now))); return { expired: Number(result.affectedRows ?? 0) }; }

const ROOM_QUESTION_COUNT = 5;
function roomCode(seed: string): string { let value = 13; for (const character of seed) value = (value * 31 + character.charCodeAt(0)) % 1_000_000; return String(value).padStart(6, "0"); }
function nextRound() { return { roundToken: randomUUID(), roundDeadline: new Date(Date.now() + MULTIPLAYER_ROUND_DURATION_MS) }; }
async function awardMatch(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, room: Awaited<ReturnType<typeof getMultiplayerRoom>>, reason: "answers" | "timeout", hostScore: number, guestScore: number, winnerUserId: number | null) {
  if (!room || !room.guestUserId) throw new Error("A complete match needs two players.");
  const guestUserId = room.guestUserId;
  const hostXp = winnerUserId === null ? 75 : winnerUserId === room.hostUserId ? 100 : 50;
  const guestXp = winnerUserId === null ? 75 : winnerUserId === room.guestUserId ? 100 : 50;
  const id = `match-${room.id}-${room.currentQuestionIndex}-${reason}`;
  return db.transaction(async (tx) => {
    const season = getSeasonDescriptor(new Date());
    await tx.insert(tournamentSeasons).values({ ...season, status: "active" as const }).onDuplicateKeyUpdate({ set: { status: "active" } });
    const [existing] = await tx.select().from(multiplayerMatches).where(eq(multiplayerMatches.id, id)).limit(1);
    if (existing) return { hostXp: existing.hostXp, guestXp: existing.guestXp };
    await tx.insert(multiplayerMatches).values({ id, roomId: room.id, seasonId: season.id, hostUserId: room.hostUserId, guestUserId, hostScore, guestScore, winnerUserId, hostXp, guestXp, resultReason: reason, completedAt: new Date() });
    for (const [userId, xp] of [[room.hostUserId, hostXp], [guestUserId, guestXp]] as const) await tx.insert(playerProgress).values({ userId, totalXp: xp, currentStreak: 0, bestStreak: 0, achievementsJson: "[]" }).onDuplicateKeyUpdate({ set: { totalXp: sql`${playerProgress.totalXp} + ${xp}` } });
    return { hostXp, guestXp };
  });
}
export async function createMultiplayerRoom(hostUserId: number, mode: GameMode) { const db = await getDb(); if (!db) throw new Error("Database not available"); const createdAt = new Date(); const id = `room-${hostUserId}-${createdAt.getTime()}-${randomUUID().slice(0, 8)}`; const room = { id, roomCode: roomCode(id), hostUserId, guestUserId: null, mode, status: "lobby" as const, currentQuestionIndex: 0, hostReady: 0, guestReady: 0, hostAnsweredIndex: -1, guestAnsweredIndex: -1, hostScore: 0, guestScore: 0, winnerUserId: null, roundToken: "", roundDeadline: null, roomVersion: 0, createdAt, updatedAt: createdAt }; await db.insert(multiplayerRooms).values(room); return room; }
export async function getMultiplayerRoom(roomId: string) { const db = await getDb(); if (!db) return undefined; const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); return room; }
export async function joinMultiplayerRoom(roomCodeValue: string, guestUserId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.roomCode, roomCodeValue)).limit(1); if (!room) throw new Error("Room not found."); if (room.status !== "lobby" || room.guestUserId) throw new Error("Room is no longer available."); if (room.hostUserId === guestUserId) throw new Error("You cannot join your own room."); const [write] = await db.update(multiplayerRooms).set({ guestUserId, roomVersion: room.roomVersion + 1 }).where(and(eq(multiplayerRooms.id, room.id), eq(multiplayerRooms.roomVersion, room.roomVersion))); if (!write.affectedRows) throw new Error("Room changed. Please reload and try again."); const joined = { ...room, guestUserId, roomVersion: room.roomVersion + 1 }; broadcastRoom(room.id, joined); return joined;
}
export async function setRoomReady(roomId: string, userId: number, ready: boolean, expectedVersion: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const room = await getMultiplayerRoom(roomId); if (!room) throw new Error("Room not found."); if (room.roomVersion !== expectedVersion) throw new Error("Room changed. Please reload and try again."); const next = getRoomReadyPatch(room, userId, ready); const start = next.status === "playing" && room.status !== "playing"; const started = start ? nextRound() : {}; const [write] = await db.update(multiplayerRooms).set({ ...next, ...started, roomVersion: expectedVersion + 1 }).where(and(eq(multiplayerRooms.id, roomId), eq(multiplayerRooms.roomVersion, expectedVersion))); if (!write.affectedRows) throw new Error("Room changed. Please reload and try again."); const updated = { ...room, ...next, ...started, roomVersion: expectedVersion + 1 }; broadcastRoom(roomId, updated); return updated;
}
export async function submitRoomAnswer(roomId: string, userId: number, questionIndex: number, answerId: string | null, roundToken: string, expectedVersion: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const room = await getMultiplayerRoom(roomId); if (!room) throw new Error("Room not found."); if (room.roomVersion !== expectedVersion) throw new Error("Room changed. Please reload and try again."); const question = VERIFIED_BIBLE_QUIZ_QUESTIONS[questionIndex % VERIFIED_BIBLE_QUIZ_QUESTIONS.length]; const next = nextRound(); const result = resolveRoomAnswer(room, userId, questionIndex, answerId, question.correctAnswer, ROOM_QUESTION_COUNT, roundToken, new Date(), next.roundToken, next.roundDeadline); const [write] = await db.update(multiplayerRooms).set({ ...result.patch, roomVersion: expectedVersion + 1 }).where(and(eq(multiplayerRooms.id, roomId), eq(multiplayerRooms.roomVersion, expectedVersion))); if (!write.affectedRows) throw new Error("Room changed. Please reload and try again."); const updated = { ...room, ...result.patch, roomVersion: expectedVersion + 1, isCorrect: result.isCorrect, questionCount: ROOM_QUESTION_COUNT }; if (result.completed) { const hostScore = "hostScore" in result.patch ? result.patch.hostScore : room.hostScore; const guestScore = "guestScore" in result.patch ? result.patch.guestScore : room.guestScore; await awardMatch(db, { ...room, ...result.patch }, "answers", hostScore, guestScore, result.patch.winnerUserId ?? null); } broadcastRoom(roomId, updated); return updated;
}
export async function timeoutRoomRound(roomId: string, userId: number, roundToken: string, expectedVersion: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const room = await getMultiplayerRoom(roomId); if (!room) throw new Error("Room not found."); if (room.roomVersion !== expectedVersion) throw new Error("Room changed. Please reload and try again."); if (room.hostUserId !== userId && room.guestUserId !== userId) throw new Error("You are not in this room."); const next = nextRound(); const result = getTimeoutPatch(room, next.roundToken, next.roundDeadline, ROOM_QUESTION_COUNT, new Date(), roundToken); const [write] = await db.update(multiplayerRooms).set({ ...result.patch, roomVersion: expectedVersion + 1 }).where(and(eq(multiplayerRooms.id, roomId), eq(multiplayerRooms.roomVersion, expectedVersion))); if (!write.affectedRows) throw new Error("Room changed. Please reload and try again."); const updated = { ...room, ...result.patch, roomVersion: expectedVersion + 1, questionCount: ROOM_QUESTION_COUNT }; if (result.completed) await awardMatch(db, { ...room, ...result.patch }, "timeout", room.hostScore, room.guestScore, result.patch.winnerUserId ?? null); broadcastRoom(roomId, updated); return updated;
}
export async function rematchMultiplayerRoom(roomId: string, userId: number, expectedVersion: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const room = await getMultiplayerRoom(roomId); if (!room) throw new Error("Room not found."); if (room.roomVersion !== expectedVersion) throw new Error("Room changed. Please reload and try again."); const next = getRematchPatch(room, userId); const [write] = await db.update(multiplayerRooms).set({ ...next, roomVersion: expectedVersion + 1 }).where(and(eq(multiplayerRooms.id, roomId), eq(multiplayerRooms.roomVersion, expectedVersion))); if (!write.affectedRows) throw new Error("Room changed. Please reload and try again."); const updated = { ...room, ...next, roomVersion: expectedVersion + 1 }; broadcastRoom(roomId, updated); return updated;
}
