export type QuestionType = "multiple_choice" | "true_false" | "unscramble" | "who_am_i";
export type VerificationStatus = "draft" | "review" | "verified" | "rejected";
export type QuestionCategory = "people" | "places" | "events" | "teachings" | "books";
export type Difficulty = "easy" | "medium" | "hard";
export type GameMode = "bible_quiz" | "bible_or_myth" | "word_puzzle" | "daily_challenge";

export interface QuestionOption {
  id: string;
  label: string;
}

export interface BibleReference {
  book: string;
  chapter: number;
  verse?: string;
  translation?: string;
}

export interface BibleQuestion {
  id: string;
  type: QuestionType;
  prompt: string;
  options: QuestionOption[];
  correctAnswer: string;
  category: QuestionCategory;
  difficulty: Difficulty;
  explanation: string;
  reference: BibleReference;
  source: string;
  status: VerificationStatus;
}

export function validateQuestion(question: BibleQuestion): string[] {
  const errors: string[] = [];
  const optionIds = new Set(question.options.map((option) => option.id));

  if (!question.id.trim()) errors.push("Question id is required.");
  if (!question.prompt.trim()) errors.push("Question prompt is required.");
  if (question.type === "multiple_choice" && question.options.length !== 4) errors.push("Multiple-choice questions require exactly four options.");
  if (question.type === "true_false" && question.options.length !== 2) errors.push("True/false questions require exactly two options.");
  if (question.type !== "unscramble" && !optionIds.has(question.correctAnswer)) errors.push("Correct answer must match an option id.");
  if (question.type === "unscramble" && !question.correctAnswer.trim()) errors.push("Unscramble questions require a canonical text answer.");
  if (!question.explanation.trim()) errors.push("Question explanation is required.");
  if (!question.reference.book.trim() || question.reference.chapter < 1) errors.push("A valid Bible reference is required.");
  if (!question.source.trim()) errors.push("Question source is required.");
  return errors;
}

export function isCompetitiveQuestion(question: BibleQuestion): boolean {
  return question.status === "verified" && validateQuestion(question).length === 0;
}

export const VERIFIED_BIBLE_QUIZ_QUESTIONS: BibleQuestion[] = [
  { id: "bq-001", type: "multiple_choice", prompt: "Who interpreted Pharaoh's dreams in Egypt?", options: [{ id: "a", label: "Moses" }, { id: "b", label: "Joseph" }, { id: "c", label: "Daniel" }, { id: "d", label: "Samuel" }], correctAnswer: "b", category: "people", difficulty: "easy", explanation: "Joseph interpreted Pharaoh's dreams and advised Egypt to prepare for seven years of famine.", reference: { book: "Genesis", chapter: 41, verse: "15-16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-002", type: "multiple_choice", prompt: "Who led the Israelites across the Red Sea?", options: [{ id: "a", label: "Joshua" }, { id: "b", label: "Aaron" }, { id: "c", label: "Moses" }, { id: "d", label: "Caleb" }], correctAnswer: "c", category: "events", difficulty: "easy", explanation: "God instructed Moses to stretch out his hand, and the sea was divided for Israel to cross.", reference: { book: "Exodus", chapter: 14, verse: "21-22" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-003", type: "multiple_choice", prompt: "In which town was Jesus born?", options: [{ id: "a", label: "Nazareth" }, { id: "b", label: "Jerusalem" }, { id: "c", label: "Bethlehem" }, { id: "d", label: "Capernaum" }], correctAnswer: "c", category: "places", difficulty: "easy", explanation: "Jesus was born in Bethlehem of Judea, the city associated with David.", reference: { book: "Matthew", chapter: 2, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-004", type: "multiple_choice", prompt: "Who defeated Goliath?", options: [{ id: "a", label: "David" }, { id: "b", label: "Saul" }, { id: "c", label: "Jonathan" }, { id: "d", label: "Gideon" }], correctAnswer: "a", category: "people", difficulty: "easy", explanation: "David trusted God and defeated Goliath with a sling and a stone.", reference: { book: "1 Samuel", chapter: 17, verse: "49-50" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-005", type: "multiple_choice", prompt: "Where are the Ten Commandments first recorded as being given to Moses?", options: [{ id: "a", label: "Mount Carmel" }, { id: "b", label: "Mount Sinai" }, { id: "c", label: "Mount of Olives" }, { id: "d", label: "Mount Tabor" }], correctAnswer: "b", category: "places", difficulty: "medium", explanation: "The covenant commands were given to Moses at Mount Sinai.", reference: { book: "Exodus", chapter: 20, verse: "1-17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-006", type: "multiple_choice", prompt: "Who stayed with Naomi and became part of the family line of David?", options: [{ id: "a", label: "Esther" }, { id: "b", label: "Ruth" }, { id: "c", label: "Hannah" }, { id: "d", label: "Miriam" }], correctAnswer: "b", category: "people", difficulty: "easy", explanation: "Ruth faithfully stayed with Naomi and later married Boaz.", reference: { book: "Ruth", chapter: 1, verse: "16-17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-007", type: "multiple_choice", prompt: "What was Jesus' first recorded sign in the Gospel of John?", options: [{ id: "a", label: "Healing a blind man" }, { id: "b", label: "Walking on water" }, { id: "c", label: "Turning water into wine" }, { id: "d", label: "Feeding five thousand" }], correctAnswer: "c", category: "events", difficulty: "medium", explanation: "At Cana, Jesus turned water into wine, revealing his glory to his disciples.", reference: { book: "John", chapter: 2, verse: "7-11" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-008", type: "multiple_choice", prompt: "Which apostle was also known as Saul before his conversion?", options: [{ id: "a", label: "Peter" }, { id: "b", label: "Paul" }, { id: "c", label: "Barnabas" }, { id: "d", label: "Silas" }], correctAnswer: "b", category: "people", difficulty: "medium", explanation: "Saul encountered Jesus on the road to Damascus and became known as Paul in his missionary ministry.", reference: { book: "Acts", chapter: 9, verse: "1-19" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-009", type: "multiple_choice", prompt: "Which prophet was sent to Nineveh and was swallowed by a great fish?", options: [{ id: "a", label: "Jonah" }, { id: "b", label: "Amos" }, { id: "c", label: "Elijah" }, { id: "d", label: "Micah" }], correctAnswer: "a", category: "people", difficulty: "easy", explanation: "Jonah was sent to Nineveh and spent three days and nights in the great fish.", reference: { book: "Jonah", chapter: 1, verse: "17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-010", type: "multiple_choice", prompt: "Where does Jesus teach the Beatitudes?", options: [{ id: "a", label: "The Sermon on the Mount" }, { id: "b", label: "The Upper Room" }, { id: "c", label: "The Temple courts" }, { id: "d", label: "The Garden of Gethsemane" }], correctAnswer: "a", category: "teachings", difficulty: "medium", explanation: "Matthew records the Beatitudes at the beginning of Jesus' Sermon on the Mount.", reference: { book: "Matthew", chapter: 5, verse: "1-12" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-011", type: "multiple_choice", prompt: "How many books are in the Protestant Old Testament?", options: [{ id: "a", label: "27" }, { id: "b", label: "39" }, { id: "c", label: "46" }, { id: "d", label: "66" }], correctAnswer: "b", category: "books", difficulty: "medium", explanation: "The Protestant Old Testament contains 39 books, from Genesis through Malachi.", reference: { book: "Genesis", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-012", type: "multiple_choice", prompt: "Who was the first king of Israel?", options: [{ id: "a", label: "David" }, { id: "b", label: "Solomon" }, { id: "c", label: "Saul" }, { id: "d", label: "Samuel" }], correctAnswer: "c", category: "people", difficulty: "easy", explanation: "Saul was anointed by Samuel as the first king of Israel at the request of the people.", reference: { book: "1 Samuel", chapter: 10, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-013", type: "multiple_choice", prompt: "Which river was Jesus baptised in?", options: [{ id: "a", label: "River Euphrates" }, { id: "b", label: "River Nile" }, { id: "c", label: "River Jordan" }, { id: "d", label: "Sea of Galilee" }], correctAnswer: "c", category: "events", difficulty: "easy", explanation: "John baptised Jesus in the River Jordan, after which the Spirit descended like a dove.", reference: { book: "Matthew", chapter: 3, verse: "13-17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-014", type: "multiple_choice", prompt: "What is the shortest book in the New Testament by word count?", options: [{ id: "a", label: "Philemon" }, { id: "b", label: "2 John" }, { id: "c", label: "3 John" }, { id: "d", label: "Jude" }], correctAnswer: "c", category: "books", difficulty: "hard", explanation: "3 John has only 219 words in the original Greek text, making it the shortest book.", reference: { book: "3 John", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-015", type: "multiple_choice", prompt: "Who was thrown into the den of lions for praying to God?", options: [{ id: "a", label: "Shadrach" }, { id: "b", label: "Daniel" }, { id: "c", label: "Nehemiah" }, { id: "d", label: "Ezra" }], correctAnswer: "b", category: "people", difficulty: "easy", explanation: "Daniel continued praying three times daily and was miraculously preserved in the lions' den.", reference: { book: "Daniel", chapter: 6, verse: "10-22" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-016", type: "multiple_choice", prompt: "Which book of the Bible records the Ten Commandments for the first time?", options: [{ id: "a", label: "Leviticus" }, { id: "b", label: "Genesis" }, { id: "c", label: "Deuteronomy" }, { id: "d", label: "Exodus" }], correctAnswer: "d", category: "books", difficulty: "medium", explanation: "The Ten Commandments are first given in Exodus 20, and later restated in Deuteronomy 5.", reference: { book: "Exodus", chapter: 20, verse: "1-17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-017", type: "multiple_choice", prompt: "Who built the first Temple in Jerusalem?", options: [{ id: "a", label: "David" }, { id: "b", label: "Solomon" }, { id: "c", label: "Hezekiah" }, { id: "d", label: "Josiah" }], correctAnswer: "b", category: "events", difficulty: "easy", explanation: "Solomon built the magnificent first Temple in Jerusalem following God's promise to David.", reference: { book: "1 Kings", chapter: 6, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-018", type: "multiple_choice", prompt: "Who wrote the largest number of epistles in the New Testament?", options: [{ id: "a", label: "Peter" }, { id: "b", label: "John" }, { id: "c", label: "Paul" }, { id: "d", label: "James" }], correctAnswer: "c", category: "books", difficulty: "medium", explanation: "The Apostle Paul wrote at least 13 New Testament letters establishing early church doctrine.", reference: { book: "Romans", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-019", type: "multiple_choice", prompt: "What test of faith did God ask of Abraham regarding his son Isaac?", options: [{ id: "a", label: "Send him to Egypt" }, { id: "b", label: "Have him consecrated as a priest" }, { id: "c", label: "Offer him as a burnt offering" }, { id: "d", label: "Build an altar on Mount Carmel" }], correctAnswer: "c", category: "events", difficulty: "medium", explanation: "God tested Abraham on Mount Moriah, then provided a ram caught in a thicket in Isaac's place.", reference: { book: "Genesis", chapter: 22, verse: "1-13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-020", type: "multiple_choice", prompt: "Which woman hid the Israelite spies in Jericho?", options: [{ id: "a", label: "Rahab" }, { id: "b", label: "Deborah" }, { id: "c", label: "Tamar" }, { id: "d", label: "Abigail" }], correctAnswer: "a", category: "people", difficulty: "medium", explanation: "Rahab sheltered the spies under stalks of flax on her roof and hung a scarlet cord in her window.", reference: { book: "Joshua", chapter: 2, verse: "1-6" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-021", type: "multiple_choice", prompt: "What does the prophetic title 'Emmanuel' mean?", options: [{ id: "a", label: "Lord of lords" }, { id: "b", label: "God with us" }, { id: "c", label: "Deliverer" }, { id: "d", label: "Everlasting Father" }], correctAnswer: "b", category: "teachings", difficulty: "easy", explanation: "Emmanuel means 'God with us', prophesied in Isaiah 7:14 and quoted in Matthew 1:23.", reference: { book: "Matthew", chapter: 1, verse: "23" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-022", type: "multiple_choice", prompt: "How many apostles did Jesus designate as his core twelve?", options: [{ id: "a", label: "7" }, { id: "b", label: "10" }, { id: "c", label: "12" }, { id: "d", label: "70" }], correctAnswer: "c", category: "events", difficulty: "easy", explanation: "Jesus chose twelve apostles after spending the night in prayer on a mountainside.", reference: { book: "Luke", chapter: 6, verse: "12-16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-023", type: "multiple_choice", prompt: "Which city's fortified walls fell after seven days of marching?", options: [{ id: "a", label: "Ai" }, { id: "b", label: "Jericho" }, { id: "c", label: "Bethlehem" }, { id: "d", label: "Hebron" }], correctAnswer: "b", category: "events", difficulty: "easy", explanation: "The walls of Jericho collapsed when the priests blew the trumpets and the people gave a great shout.", reference: { book: "Joshua", chapter: 6, verse: "20" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-024", type: "multiple_choice", prompt: "Which prophet had his lips cleansed by a live coal touched by a seraph?", options: [{ id: "a", label: "Jeremiah" }, { id: "b", label: "Ezekiel" }, { id: "c", label: "Isaiah" }, { id: "d", label: "Amos" }], correctAnswer: "c", category: "people", difficulty: "hard", explanation: "In his heavenly vision, a seraph touched Isaiah's mouth with a hot coal, taking away his iniquity.", reference: { book: "Isaiah", chapter: 6, verse: "6-7" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-025", type: "multiple_choice", prompt: "Who was the mother of John the Baptist?", options: [{ id: "a", label: "Mary" }, { id: "b", label: "Anna" }, { id: "c", label: "Elizabeth" }, { id: "d", label: "Martha" }], correctAnswer: "c", category: "people", difficulty: "easy", explanation: "Elizabeth, wife of the priest Zechariah, gave birth to John in her advanced years as God promised.", reference: { book: "Luke", chapter: 1, verse: "13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-026", type: "multiple_choice", prompt: "In the Parable of the Prodigal Son, what three gifts did the father bestow upon the son's return?", options: [{ id: "a", label: "Gold, frankincense, and myrrh" }, { id: "b", label: "A sword, a shield, and a horse" }, { id: "c", label: "The best robe, a ring, and sandals" }, { id: "d", label: "A new flock, silver, and grain" }], correctAnswer: "c", category: "teachings", difficulty: "medium", explanation: "The father commanded his servants: 'Bring the best robe and put it on him; put a ring on his finger and sandals on his feet.'", reference: { book: "Luke", chapter: 15, verse: "22" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-027", type: "multiple_choice", prompt: "For what sum did Judas Iscariot agree to betray Jesus?", options: [{ id: "a", label: "Ten gold coins" }, { id: "b", label: "Thirty pieces of silver" }, { id: "c", label: "Fifty shekels" }, { id: "d", label: "A talent of silver" }], correctAnswer: "b", category: "events", difficulty: "easy", explanation: "Judas was paid thirty pieces of silver, fulfilling the prophetic price mentioned in Zechariah 11:12.", reference: { book: "Matthew", chapter: 26, verse: "15" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-028", type: "multiple_choice", prompt: "Which psalm begins with the declaration: 'The LORD is my shepherd; I shall not want'?", options: [{ id: "a", label: "Psalm 1" }, { id: "b", label: "Psalm 22" }, { id: "c", label: "Psalm 23" }, { id: "d", label: "Psalm 91" }], correctAnswer: "c", category: "books", difficulty: "easy", explanation: "Psalm 23 is David's beloved psalm of trust in God's protective and restoring pastoral care.", reference: { book: "Psalms", chapter: 23, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-029", type: "multiple_choice", prompt: "In which village did Jesus raise his friend Lazarus from the tomb?", options: [{ id: "a", label: "Capernaum" }, { id: "b", label: "Bethany" }, { id: "c", label: "Nain" }, { id: "d", label: "Bethsaida" }], correctAnswer: "b", category: "places", difficulty: "medium", explanation: "Bethany was the home of Mary, Martha, and Lazarus, situated about two miles from Jerusalem.", reference: { book: "John", chapter: 11, verse: "1,43-44" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-030", type: "multiple_choice", prompt: "How many qualities comprise the Fruit of the Spirit in Galatians 5?", options: [{ id: "a", label: "Seven" }, { id: "b", label: "Nine" }, { id: "c", label: "Twelve" }, { id: "d", label: "Ten" }], correctAnswer: "b", category: "teachings", difficulty: "medium", explanation: "Galatians 5:22-23 lists nine qualities: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.", reference: { book: "Galatians", chapter: 5, verse: "22-23" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-031", type: "multiple_choice", prompt: "Which disciple declared he would not believe the resurrection without seeing the nail marks?", options: [{ id: "a", label: "Peter" }, { id: "b", label: "Andrew" }, { id: "c", label: "Thomas" }, { id: "d", label: "Philip" }], correctAnswer: "c", category: "people", difficulty: "easy", explanation: "Thomas doubted until Jesus appeared in the Upper Room and invited him to touch his wounds.", reference: { book: "John", chapter: 20, verse: "25-28" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-032", type: "multiple_choice", prompt: "What gift did King Solomon ask of God at Gibeon?", options: [{ id: "a", label: "Long life" }, { id: "b", label: "An understanding heart to judge the people" }, { id: "c", label: "Victory over enemies" }, { id: "d", label: "Immense wealth" }], correctAnswer: "b", category: "people", difficulty: "easy", explanation: "Solomon asked for wisdom to govern God's people, and God gave him both wisdom and unprecedented wealth.", reference: { book: "1 Kings", chapter: 3, verse: "9-13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-033", type: "multiple_choice", prompt: "On what island was the Apostle Paul shipwrecked during his journey to Rome?", options: [{ id: "a", label: "Crete" }, { id: "b", label: "Cyprus" }, { id: "c", label: "Malta" }, { id: "d", label: "Patmos" }], correctAnswer: "c", category: "places", difficulty: "hard", explanation: "Paul and everyone aboard safely reached the shores of Malta after two weeks in the storm.", reference: { book: "Acts", chapter: 28, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-034", type: "multiple_choice", prompt: "On which creation day did God form man in his own image?", options: [{ id: "a", label: "Fourth day" }, { id: "b", label: "Fifth day" }, { id: "c", label: "Sixth day" }, { id: "d", label: "Seventh day" }], correctAnswer: "c", category: "events", difficulty: "easy", explanation: "God created land animals and humanity on the sixth day before resting on the seventh.", reference: { book: "Genesis", chapter: 1, verse: "26-31" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-035", type: "multiple_choice", prompt: "Which New Testament book directly follows the four Gospels?", options: [{ id: "a", label: "Romans" }, { id: "b", label: "Acts of the Apostles" }, { id: "c", label: "Hebrews" }, { id: "d", label: "Galatians" }], correctAnswer: "b", category: "books", difficulty: "easy", explanation: "Acts follows John and chronicles the Holy Spirit's empowerment of the early church.", reference: { book: "Acts", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-036", type: "multiple_choice", prompt: "On which Aegean island was John exiled when he received the Revelation?", options: [{ id: "a", label: "Rhodes" }, { id: "b", label: "Crete" }, { id: "c", label: "Patmos" }, { id: "d", label: "Corfu" }], correctAnswer: "c", category: "places", difficulty: "medium", explanation: "John was on the island called Patmos on account of the word of God and the testimony of Jesus.", reference: { book: "Revelation", chapter: 1, verse: "9" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-037", type: "multiple_choice", prompt: "What is often referred to as the 'Golden Rule' taught by Jesus?", options: [{ id: "a", label: "Turn the other cheek" }, { id: "b", label: "Do to others whatever you would like them to do to you" }, { id: "c", label: "Give to Caesar what is Caesar's" }, { id: "d", label: "Seek first the kingdom of God" }], correctAnswer: "b", category: "teachings", difficulty: "easy", explanation: "Matthew 7:12: 'So whatever you wish that others would do to you, do also to them.'", reference: { book: "Matthew", chapter: 7, verse: "12" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-038", type: "multiple_choice", prompt: "Who was the father of the twelve sons who became the tribes of Israel?", options: [{ id: "a", label: "Abraham" }, { id: "b", label: "Isaac" }, { id: "c", label: "Jacob" }, { id: "d", label: "Joseph" }], correctAnswer: "c", category: "people", difficulty: "easy", explanation: "Jacob's name was changed to Israel after wrestling with God; his twelve sons founded the tribes.", reference: { book: "Genesis", chapter: 35, verse: "10,22-26" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-039", type: "multiple_choice", prompt: "How many baskets of leftover fragments were gathered after the feeding of the five thousand?", options: [{ id: "a", label: "Seven" }, { id: "b", label: "Ten" }, { id: "c", label: "Twelve" }, { id: "d", label: "Three" }], correctAnswer: "c", category: "events", difficulty: "easy", explanation: "The disciples picked up twelve full baskets of broken pieces that remained.", reference: { book: "Matthew", chapter: 14, verse: "20" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-040", type: "multiple_choice", prompt: "In which garden did Jesus endure intense sorrow and pray before his arrest?", options: [{ id: "a", label: "Garden of Eden" }, { id: "b", label: "Garden of Gethsemane" }, { id: "c", label: "Garden of Shushan" }, { id: "d", label: "The King's Garden" }], correctAnswer: "b", category: "places", difficulty: "medium", explanation: "Jesus prayed in Gethsemane on the Mount of Olives: 'Not my will, but yours be done.'", reference: { book: "Matthew", chapter: 26, verse: "36-46" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-041", type: "multiple_choice", prompt: "Which Old Testament book records the trial, losses, and steadfast integrity of an Uzite patriarch?", options: [{ id: "a", label: "Ecclesiastes" }, { id: "b", label: "Proverbs" }, { id: "c", label: "Job" }, { id: "d", label: "Lamentations" }], correctAnswer: "c", category: "books", difficulty: "easy", explanation: "The Book of Job examines the problem of innocent suffering and God's sovereign majesty.", reference: { book: "Job", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-042", type: "multiple_choice", prompt: "What covenant sign did God establish in the sky following the great flood?", options: [{ id: "a", label: "A pillar of cloud" }, { id: "b", label: "A rainbow" }, { id: "c", label: "A burning star" }, { id: "d", label: "A golden crown" }], correctAnswer: "b", category: "events", difficulty: "easy", explanation: "God placed the rainbow as the eternal token of his covenant never again to submerge the whole earth.", reference: { book: "Genesis", chapter: 9, verse: "13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-043", type: "multiple_choice", prompt: "What ancient brick tower was halted when human speech was diversified into mutually unintelligible tongues?", options: [{ id: "a", label: "Tower of David" }, { id: "b", label: "Tower of Babel" }, { id: "c", label: "Tower of Siloam" }, { id: "d", label: "Tower of Antonia" }], correctAnswer: "b", category: "places", difficulty: "easy", explanation: "At Babel, humanity sought to build a tower to heaven, so the Lord scattered them across the earth.", reference: { book: "Genesis", chapter: 11, verse: "1-9" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-044", type: "multiple_choice", prompt: "In Jesus' parable of the talents, what did the third servant do with his single talent?", options: [{ id: "a", label: "He traded it and doubled it" }, { id: "b", label: "He lost it to thieves" }, { id: "c", label: "He dug a hole in the ground and hid it" }, { id: "d", label: "He lent it at interest" }], correctAnswer: "c", category: "teachings", difficulty: "medium", explanation: "The unfaithful servant buried his talent in the dirt out of fear and sloth.", reference: { book: "Matthew", chapter: 25, verse: "18,25" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-045", type: "multiple_choice", prompt: "What does the Hebrew exclamation 'Hallelujah' literally express?", options: [{ id: "a", label: "Praise Yahweh (the LORD)" }, { id: "b", label: "Holy is the sanctuary" }, { id: "c", label: "God is our shield" }, { id: "d", label: "Peace be upon Israel" }], correctAnswer: "a", category: "teachings", difficulty: "medium", explanation: "'Hallelu' is the imperative 'Praise ye', and 'Yah' is the shortened sacred covenant name of God.", reference: { book: "Psalms", chapter: 148, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-046", type: "multiple_choice", prompt: "To which tribe of Israel did Moses and Aaron belong?", options: [{ id: "a", label: "Judah" }, { id: "b", label: "Levi" }, { id: "c", label: "Benjamin" }, { id: "d", label: "Ephraim" }], correctAnswer: "b", category: "people", difficulty: "hard", explanation: "Amram and Jochebed, Moses' parents, were both of the house of Levi.", reference: { book: "Exodus", chapter: 2, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-047", type: "multiple_choice", prompt: "What astronomical guidance guided the Magi to the place of the young Messiah?", options: [{ id: "a", label: "A comet" }, { id: "b", label: "A brilliant star in the east" }, { id: "c", label: "A solar eclipse" }, { id: "d", label: "An angelic constellation" }], correctAnswer: "b", category: "events", difficulty: "easy", explanation: "The Magi saw his star rising and followed it until it rested over the house in Bethlehem.", reference: { book: "Matthew", chapter: 2, verse: "2,9" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-048", type: "multiple_choice", prompt: "What was the first of the ten plagues brought upon Egypt through Aaron's rod?", options: [{ id: "a", label: "Frogs covering the land" }, { id: "b", label: "Swarms of gnats" }, { id: "c", label: "Water turning into blood" }, { id: "d", label: "Darkness for three days" }], correctAnswer: "c", category: "events", difficulty: "medium", explanation: "The waters of the Nile and all Egyptian streams were turned into blood so that fish died.", reference: { book: "Exodus", chapter: 7, verse: "20-21" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-049", type: "multiple_choice", prompt: "Which prophet was dispatched to Bethlehem to anoint David among Jesse's sons?", options: [{ id: "a", label: "Nathan" }, { id: "b", label: "Eli" }, { id: "c", label: "Samuel" }, { id: "d", label: "Elijah" }], correctAnswer: "c", category: "events", difficulty: "medium", explanation: "Samuel consecrated Jesse and his sons, passing by seven older brothers until David was summoned from the sheep.", reference: { book: "1 Samuel", chapter: 16, verse: "11-13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bq-050", type: "multiple_choice", prompt: "In which biblical language was nearly the entirety of the Old Testament composed?", options: [{ id: "a", label: "Koine Greek" }, { id: "b", label: "Classical Latin" }, { id: "c", label: "Biblical Hebrew" }, { id: "d", label: "Syriac" }], correctAnswer: "c", category: "books", difficulty: "medium", explanation: "The Tanakh was written in Ancient Hebrew, with a few chapters in Ezra and Daniel in Aramaic.", reference: { book: "Genesis", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
];

export const VERIFIED_BIBLE_OR_MYTH_QUESTIONS: BibleQuestion[] = [
  { id: "bm-001", type: "true_false", prompt: "The Bible says that Adam and Eve ate an apple in the Garden of Eden.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "events", difficulty: "easy", explanation: "Genesis names the tree and its fruit but does not identify the fruit as an apple.", reference: { book: "Genesis", chapter: 3, verse: "6" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-002", type: "true_false", prompt: "The Bible says that Noah took two of every kind of clean animal onto the ark.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "events", difficulty: "medium", explanation: "Genesis distinguishes between clean animals, taken in greater numbers, and other animals, taken in pairs.", reference: { book: "Genesis", chapter: 7, verse: "2-3" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-003", type: "true_false", prompt: "The Bible says that Jesus fed five thousand men with five loaves and two fish.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "easy", explanation: "The feeding of the five thousand is recorded with five loaves and two fish.", reference: { book: "Matthew", chapter: 14, verse: "17-21" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-004", type: "true_false", prompt: "The Bible names the three wise men who visited Jesus.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "people", difficulty: "medium", explanation: "Matthew records wise men from the east but does not give their number or names.", reference: { book: "Matthew", chapter: 2, verse: "1-12" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-005", type: "true_false", prompt: "The Bible says that David used a sling and a stone against Goliath.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "easy", explanation: "David selected five smooth stones and defeated Goliath with a sling and a stone.", reference: { book: "1 Samuel", chapter: 17, verse: "40,49-50" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-006", type: "true_false", prompt: "The Book of Jonah specifies that Jonah was swallowed by a great blue whale.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "events", difficulty: "medium", explanation: "Jonah 1:17 uses the Hebrew phrase 'dag gadol' (great fish), not specifying the mammalian whale species.", reference: { book: "Jonah", chapter: 1, verse: "17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-007", type: "true_false", prompt: "Mary Magdalene was the first witness recorded to see and speak with the risen Christ.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "people", difficulty: "medium", explanation: "John 20:14-17 and Mark 16:9 confirm Jesus appeared first to Mary Magdalene early on the first day of the week.", reference: { book: "John", chapter: 20, verse: "14-16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-008", type: "true_false", prompt: "Samson's supernatural physical power resided biochemically within his hair fibers.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "people", difficulty: "hard", explanation: "Samson's strength came from the Spirit of the Lord through his consecrated Nazirite vow, of which the uncut hair was the sign.", reference: { book: "Judges", chapter: 16, verse: "17,20" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-009", type: "true_false", prompt: "The disciples of Jesus were first designated by the label 'Christians' at Syrian Antioch.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "hard", explanation: "Acts 11:26 states: 'And in Antioch the disciples were first called Christians.'", reference: { book: "Acts", chapter: 11, verse: "26" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-010", type: "true_false", prompt: "In the Genesis account, the cunning serpent conversed audibly with the woman.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "medium", explanation: "Genesis 3 records a direct spoken dialogue between the serpent and the woman regarding the forbidden fruit.", reference: { book: "Genesis", chapter: 3, verse: "1-5" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-011", type: "true_false", prompt: "Elijah ascended into heaven carried up in a whirlwind accompanied by horses of fire.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "medium", explanation: "2 Kings 2:11 notes: 'behold, chariots of fire and horses of fire separated the two of them. And Elijah went up by a whirlwind into heaven.'", reference: { book: "2 Kings", chapter: 2, verse: "11" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-012", type: "true_false", prompt: "The Bible asserts that money in and of itself is the origin of all wickedness.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "teachings", difficulty: "medium", explanation: "1 Timothy 6:10 warns that 'the love of money is a root of all kinds of evils', not physical currency itself.", reference: { book: "1 Timothy", chapter: 6, verse: "10" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-013", type: "true_false", prompt: "God rested on the seventh creation day because the divine energy had been exhausted.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "myth", category: "teachings", difficulty: "hard", explanation: "God rested to sanctify the rhythm of creation; Isaiah 40:28 affirms: 'The LORD is the everlasting God... he does not faint or grow weary.'", reference: { book: "Isaiah", chapter: 40, verse: "28" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-014", type: "true_false", prompt: "Paul and Silas sang hymns and prayed while bound in stocks in a Philippian jail.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "medium", explanation: "Acts 16:25 states: 'About midnight Paul and Silas were praying and singing hymns to God, and the prisoners were listening to them.'", reference: { book: "Acts", chapter: 16, verse: "25" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-015", type: "true_false", prompt: "The biblical genealogy records that Methuselah attained the age of 969 years.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "people", difficulty: "easy", explanation: "Genesis 5:27 records: 'Thus all the days of Methuselah were 969 years, and he died.'", reference: { book: "Genesis", chapter: 5, verse: "27" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-016", type: "true_false", prompt: "John the Baptist's wilderness diet included locusts and wild forest honey.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "people", difficulty: "easy", explanation: "Matthew 3:4 details John's garment of camel hair, leather belt, and food of locusts and wild honey.", reference: { book: "Matthew", chapter: 3, verse: "4" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-017", type: "true_false", prompt: "The burning bush observed by Moses was enveloped in flame yet remained unconsumed.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "easy", explanation: "Exodus 3:2: 'the bush was burning, yet it was not consumed.'", reference: { book: "Exodus", chapter: 3, verse: "2" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-018", type: "true_false", prompt: "The shortest recorded verse in the New Testament is 'Jesus wept.'", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "easy", explanation: "John 11:35 contains merely two words in English: 'Jesus wept', expressing profound compassion at Lazarus' tomb.", reference: { book: "John", chapter: 11, verse: "35" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-019", type: "true_false", prompt: "Abraham had reached 100 years of age when Isaac was born unto him through Sarah.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "people", difficulty: "medium", explanation: "Genesis 21:5 states: 'Abraham was a hundred years old when his son Isaac was born to him.'", reference: { book: "Genesis", chapter: 21, verse: "5" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "bm-020", type: "true_false", prompt: "Roman soldiers cast lots for Jesus' seamless tunic at the foot of the cross.", options: [{ id: "bible", label: "Bible" }, { id: "myth", label: "Myth" }], correctAnswer: "bible", category: "events", difficulty: "medium", explanation: "John 19:24 records the soldiers saying: 'Let us not tear it, but cast lots for it to see whose it shall be.'", reference: { book: "John", chapter: 19, verse: "24" }, source: "Bible Arena verified seed bank", status: "verified" },
];

export const VERIFIED_WORD_PUZZLE_QUESTIONS: BibleQuestion[] = [
  { id: "wp-001", type: "unscramble", prompt: "Unscramble this Bible prophet: H A N O J", options: [], correctAnswer: "jonah", category: "people", difficulty: "easy", explanation: "Jonah was the prophet called to preach repentance to the capital city of Nineveh.", reference: { book: "Jonah", chapter: 1, verse: "1-2" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-002", type: "unscramble", prompt: "Unscramble this faithful woman: H T U R", options: [], correctAnswer: "ruth", category: "people", difficulty: "easy", explanation: "Ruth pledged loyalty to Naomi and became great-grandmother to King David.", reference: { book: "Ruth", chapter: 1, verse: "16-17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-003", type: "unscramble", prompt: "Unscramble our Lord's name: S U S E J", options: [], correctAnswer: "jesus", category: "people", difficulty: "easy", explanation: "Jesus is the Christ, Son of the Living God, whose name signifies 'Yahweh saves'.", reference: { book: "Matthew", chapter: 1, verse: "21" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-004", type: "unscramble", prompt: "Unscramble this fruit of the Spirit: C E A P E", options: [], correctAnswer: "peace", category: "teachings", difficulty: "medium", explanation: "Peace (Shalom) surpasses all human understanding and guards our hearts in Christ.", reference: { book: "Philippians", chapter: 4, verse: "7" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-005", type: "unscramble", prompt: "Unscramble this divine gift: E G R A C", options: [], correctAnswer: "grace", category: "teachings", difficulty: "medium", explanation: "By grace we have been saved through faith, a free gift of God not earned by works.", reference: { book: "Ephesians", chapter: 2, verse: "8-9" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-006", type: "unscramble", prompt: "Unscramble the lawgiver of Israel: S O E M S", options: [], correctAnswer: "moses", category: "people", difficulty: "easy", explanation: "Moses spoke face to face with God and led the Israelites out of Egyptian servitude.", reference: { book: "Exodus", chapter: 3, verse: "4" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-007", type: "unscramble", prompt: "Unscramble the shepherd king: D I V A D", options: [], correctAnswer: "david", category: "people", difficulty: "easy", explanation: "David was anointed by Samuel, felled Goliath, and established the royal dynasty.", reference: { book: "1 Samuel", chapter: 16, verse: "13" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-008", type: "unscramble", prompt: "Unscramble the substance of things hoped for: I T F H A", options: [], correctAnswer: "faith", category: "teachings", difficulty: "easy", explanation: "Without faith it is impossible to please God, for whoever comes to him must believe he exists.", reference: { book: "Hebrews", chapter: 11, verse: "1,6" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-009", type: "unscramble", prompt: "Unscramble the wisest king: L M N O O O S", options: [], correctAnswer: "solomon", category: "people", difficulty: "medium", explanation: "Solomon governed unified Israel during its golden age of wisdom, diplomacy, and architecture.", reference: { book: "1 Kings", chapter: 3, verse: "12" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-010", type: "unscramble", prompt: "Unscramble God's spokesperson: H P O E R P T", options: [], correctAnswer: "prophet", category: "people", difficulty: "medium", explanation: "Prophets declared God's holy counsel, calling nations back to righteousness.", reference: { book: "Jeremiah", chapter: 1, verse: "5" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-011", type: "unscramble", prompt: "Unscramble the chosen messengers: L E P P S O T A", options: [], correctAnswer: "apostles", category: "people", difficulty: "medium", explanation: "The apostles were sent forth by Jesus to make disciples of all nations.", reference: { book: "Matthew", chapter: 28, verse: "19" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-012", type: "unscramble", prompt: "Unscramble the friend of God: B A H R A A M", options: [], correctAnswer: "abraham", category: "people", difficulty: "medium", explanation: "Abraham believed the divine promise and was credited with enduring righteousness.", reference: { book: "Genesis", chapter: 15, verse: "6" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-013", type: "unscramble", prompt: "Unscramble the book of 150 songs: Y P S A L M", options: [], correctAnswer: "psalms", category: "books", difficulty: "easy", explanation: "The Psalms provide the worship prayer-book for Israel and the worldwide church.", reference: { book: "Psalms", chapter: 1, verse: "1" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-014", type: "unscramble", prompt: "Unscramble the good news message: S O G L P E", options: [], correctAnswer: "gospel", category: "books", difficulty: "easy", explanation: "The Gospel is the power of God for salvation to everyone who believes.", reference: { book: "Romans", chapter: 1, verse: "16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-015", type: "unscramble", prompt: "Unscramble communion with God: R E Y A P R", options: [], correctAnswer: "prayer", category: "teachings", difficulty: "easy", explanation: "Pray without ceasing, presenting your requests with thanksgiving unto God.", reference: { book: "1 Thessalonians", chapter: 5, verse: "17" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-016", type: "unscramble", prompt: "Unscramble God's sacred pledge: T N A N E V O C", options: [], correctAnswer: "covenant", category: "teachings", difficulty: "medium", explanation: "The new covenant in Christ's blood offers eternal forgiveness and reconciliation.", reference: { book: "Hebrews", chapter: 9, verse: "15" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-017", type: "unscramble", prompt: "Unscramble the prophet in Babylon: L E I A N D", options: [], correctAnswer: "daniel", category: "people", difficulty: "medium", explanation: "Daniel maintained purity, interpreted kings' dreams, and foresaw God's everlasting kingdom.", reference: { book: "Daniel", chapter: 2, verse: "44" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-018", type: "unscramble", prompt: "Unscramble the Persian queen of faith: H T E S R E", options: [], correctAnswer: "esther", category: "people", difficulty: "medium", explanation: "Queen Esther risked her crown and life to secure the salvation of the Jewish people.", reference: { book: "Esther", chapter: 4, verse: "16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-019", type: "unscramble", prompt: "Unscramble the greatest commandment: E V O L", options: [], correctAnswer: "love", category: "teachings", difficulty: "easy", explanation: "God is love, and whoever abides in love abides in God, and God in him.", reference: { book: "1 John", chapter: 4, verse: "16" }, source: "Bible Arena verified seed bank", status: "verified" },
  { id: "wp-020", type: "unscramble", prompt: "Unscramble the giant of Gath: G O L I A H T", options: [], correctAnswer: "goliath", category: "people", difficulty: "easy", explanation: "Goliath defied the armies of the living God before being struck down by David.", reference: { book: "1 Samuel", chapter: 17, verse: "45" }, source: "Bible Arena verified seed bank", status: "verified" },
];

export function getVerifiedQuestions(count = 10): BibleQuestion[] {
  const eligible = VERIFIED_BIBLE_QUIZ_QUESTIONS.filter(isCompetitiveQuestion);
  if (eligible.length < count) throw new Error("Not enough verified Bible Quiz questions for this session.");
  return eligible.slice(0, count);
}

export function getVerifiedQuestionsForMode(mode: GameMode, count: number, shuffle = false): BibleQuestion[] {
  const source = mode === "bible_or_myth"
    ? VERIFIED_BIBLE_OR_MYTH_QUESTIONS
    : mode === "word_puzzle"
      ? VERIFIED_WORD_PUZZLE_QUESTIONS
      : VERIFIED_BIBLE_QUIZ_QUESTIONS;
  const eligible = source.filter(isCompetitiveQuestion);
  if (eligible.length < count) throw new Error(`Not enough verified questions for ${mode}.`);
  if (mode === "daily_challenge") {
    const dayKey = new Date().toISOString().slice(0, 10);
    const offset = [...dayKey].reduce((total, character) => total + character.charCodeAt(0), 0) % eligible.length;
    return Array.from({ length: count }, (_, index) => eligible[(offset + index) % eligible.length]);
  }
  if (!shuffle) return eligible.slice(0, count);
  const shuffled = [...eligible].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getVerifiedQuestionById(mode: GameMode, id: string): BibleQuestion | undefined {
  const pool = mode === "bible_or_myth"
    ? VERIFIED_BIBLE_OR_MYTH_QUESTIONS
    : mode === "word_puzzle"
      ? VERIFIED_WORD_PUZZLE_QUESTIONS
      : VERIFIED_BIBLE_QUIZ_QUESTIONS;
  return pool.find((question) => question.id === id && isCompetitiveQuestion(question));
}
