plugins { id 'com.android.application' }
android {
    namespace 'com.holaoluwakintan.biblearena'
    compileSdk 36
    defaultConfig {
        applicationId 'com.holaoluwakintan.biblearena'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging { jniLibs { useLegacyPackaging true } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    lint { checkReleaseBuilds false; abortOnError false }
    dependenciesInfo { includeInApk false; includeInBundle false }
}
dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
}
